name: easy_logger
description: Easy logger
version: 0.0.3

environment:
  sdk: '>=2.17.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3

flutter: